import 'package:flutter/material.dart' hide Notification;
import 'package:provider/provider.dart';
import '../services/gamification_service.dart';
import 'package:intl/intl.dart';
import '../database/database.dart';
import '../providers/user_session.dart';

class NotificationsScreen extends StatefulWidget {
  const NotificationsScreen({super.key});

  @override
  State<NotificationsScreen> createState() => _NotificationsScreenState();
}

class _NotificationsScreenState extends State<NotificationsScreen> {
  List<Notification> _notifications = [];
  bool _isLoading = true;

  @override
  void initState() {
    super.initState();
    _loadNotifications();
  }

  Future<void> _loadNotifications() async {
    final userSession = context.read<UserSession>();
    final currentUser = userSession.currentUser;
    if (currentUser == null) return;

    setState(() => _isLoading = true);
    
    final notificationsDao = context.read<NotificationsDao>();
    final list = await notificationsDao.getNotifications(currentUser.id);

    if (mounted) {
      setState(() {
        _notifications = list;
        _isLoading = false;
      });
      // Mark all as read when opening screen
      // notificationsDao.markAllAsRead(currentUser.id);
    }
  }
  
  Future<void> _markAsRead(Notification notification) async {
    if (notification.isRead) return;
    
    final notificationsDao = context.read<NotificationsDao>();
    await notificationsDao.markAsRead(notification.id);
    
    // Update local state to reflect change immediately
    setState(() {
      final index = _notifications.indexWhere((n) => n.id == notification.id);
      if (index != -1) {
        // Create a copy with isRead = true. 
        // Since generated data classes are immutable (usually), we rely on copyWith if available or just reload.
        // Drift classes have copyWith.
        // But Notification class is generated by Drift.
        // Let's just reload for simplicity or ignore local update visual cue if it's subtle.
        // Actually, let's keep it simple and just mark read in DB. 
        // The list won't update visually until reload, but we can manually update list if needed.
        _loadNotifications();
      }
    });
  }

  Future<void> _markAllRead() async {
     final userSession = context.read<UserSession>();
    final currentUser = userSession.currentUser;
    if (currentUser == null) return;
    
    final notificationsDao = context.read<NotificationsDao>();
    await notificationsDao.markAllAsRead(currentUser.id);
    _loadNotifications();
  }

  Future<void> _handleFriendRequest(Notification notification, bool accept) async {
    final userSession = context.read<UserSession>();
    final currentUser = userSession.currentUser;
    if (currentUser == null || notification.relatedId == null) return;

    final friendshipsDao = context.read<FriendshipsDao>();
    final gamificationService = context.read<GamificationService>(); // Moved up
    
    try {
      final pendingRequests = await friendshipsDao.getPendingRequests(currentUser.id);
      final request = pendingRequests.firstWhere(
        (r) => r.user.id == notification.relatedId, 
      );

      if (accept) {
        await friendshipsDao.acceptFriendRequest(request.friendship.id);
        
        // Gamification Hook: +10 XP
        if (mounted) {
          await gamificationService.addXp(currentUser.id, 10);
        }

         if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Friend request accepted! (+10 XP)'), backgroundColor: Colors.green));
        }
      } else {
        await friendshipsDao.rejectFriendRequest(request.friendship.id);
         if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Friend request rejected')));
        }
      }
      await _markAsRead(notification);
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Request not found or already handled')));
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final mutedColor = theme.inputDecorationTheme.hintStyle?.color ?? Colors.grey;

    return Scaffold(
      backgroundColor: theme.scaffoldBackgroundColor,
      appBar: AppBar(
        title: Text('Notifications', style: TextStyle(color: theme.colorScheme.onSurface)),
        backgroundColor: Colors.transparent,
        elevation: 0,
        iconTheme: IconThemeData(color: theme.colorScheme.onSurface),
        actions: [
          IconButton(
            icon: const Icon(Icons.done_all),
            tooltip: 'Mark all as read',
            onPressed: _markAllRead,
          ),
        ],
      ),
      body: _isLoading
          ? Center(child: CircularProgressIndicator(color: theme.primaryColor))
          : _notifications.isEmpty
              ? _buildEmptyState(mutedColor)
              : ListView.builder(
                  itemCount: _notifications.length,
                  itemBuilder: (context, index) {
                    return _buildNotificationItem(_notifications[index], theme, mutedColor);
                  },
                ),
    );
  }

  Widget _buildEmptyState(Color mutedColor) {
    return Center(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Icon(Icons.notifications_none, size: 64, color: mutedColor.withValues(alpha:0.5)),
          const SizedBox(height: 16),
          Text('No notifications', style: TextStyle(color: mutedColor, fontSize: 18)),
        ],
      ),
    );
  }

  void _showNotificationDialog(Notification notification, ThemeData theme) {
    IconData icon;
    Color color;
    String headerText = 'NOTIFICATION';

    bool isDefeat = notification.title.toLowerCase().contains('failed') || 
                    notification.title.toLowerCase().contains('defeat') ||
                    notification.title.toLowerCase().contains('lost');

    switch (notification.type) {
      case 'friend_request':
        icon = Icons.person_add;
        color = Colors.blueAccent;
        headerText = 'NEW FRIEND';
        break;
      case 'match_result':
        if (isDefeat) {
           icon = Icons.sentiment_very_dissatisfied; 
           color = Colors.redAccent;
           headerText = 'DEFEAT';
        } else {
           icon = Icons.emoji_events;
           color = Colors.amber;
           headerText = 'VICTORY!';
        }
        break;
      default:
        icon = Icons.info_outline;
        color = theme.primaryColor;
    }

    showDialog(
      context: context,
      builder: (context) => Dialog(
        backgroundColor: Colors.transparent,
        child: Container(
          decoration: BoxDecoration(
            color: theme.cardTheme.color,
            borderRadius: BorderRadius.circular(24),
            border: Border.all(color: theme.colorScheme.onSurface.withValues(alpha: 0.1)),
            boxShadow: [
               BoxShadow(color: Colors.black.withValues(alpha: 0.5), blurRadius: 20, offset: const Offset(0, 10))
            ]
          ),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
               // Header with Icon
               Container(
                  width: double.infinity,
                  padding: const EdgeInsets.symmetric(vertical: 24),
                  decoration: BoxDecoration(
                     color: color.withValues(alpha: 0.1),
                     borderRadius: const BorderRadius.only(topLeft: Radius.circular(24), topRight: Radius.circular(24)),
                  ),
                  child: Column(
                    children: [
                       Container(
                          padding: const EdgeInsets.all(16),
                          decoration: BoxDecoration(
                             color: theme.cardTheme.color,
                             shape: BoxShape.circle,
                             border: Border.all(color: color.withValues(alpha: 0.5), width: 2),
                             boxShadow: [
                                BoxShadow(color: color.withValues(alpha: 0.3), blurRadius: 12)
                             ]
                          ),
                          child: Icon(icon, size: 32, color: color),
                       ),
                       const SizedBox(height: 12),
                       Text(
                          headerText, 
                          style: TextStyle(color: color, fontWeight: FontWeight.bold, letterSpacing: 1.5, fontSize: 12)
                       )
                    ],
                  ),
               ),
               
               // Content
               Padding(
                  padding: const EdgeInsets.all(24),
                  child: Column(
                     children: [
                        Text(
                           notification.title,
                           textAlign: TextAlign.center,
                           style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold, color: theme.colorScheme.onSurface),
                        ),
                        const SizedBox(height: 12),
                        Text(
                           notification.message,
                           textAlign: TextAlign.center,
                           style: TextStyle(fontSize: 14, height: 1.5, color: theme.colorScheme.onSurface.withValues(alpha: 0.7)),
                        ),
                        const SizedBox(height: 24),
                        Divider(color: theme.colorScheme.onSurface.withValues(alpha: 0.1)),
                        const SizedBox(height: 8),
                         Text(
                            DateFormat('MMMM d, y • h:mm a').format(notification.createdAt),
                            style: TextStyle(color: theme.inputDecorationTheme.hintStyle?.color?.withValues(alpha: 0.5), fontSize: 11),
                         ),
                     ],
                  ),
               ),
               
               // Actions
               Padding(
                  padding: const EdgeInsets.fromLTRB(24, 0, 24, 24),
                  child: SizedBox(
                     width: double.infinity,
                     child: ElevatedButton(
                        style: ElevatedButton.styleFrom(
                           backgroundColor: theme.colorScheme.surface,
                           foregroundColor: theme.colorScheme.onSurface,
                           elevation: 0,
                           shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                           padding: const EdgeInsets.symmetric(vertical: 16)
                        ),
                        onPressed: () => Navigator.pop(context),
                        child: const Text('Close'),
                     ),
                  ),
               )
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildNotificationItem(Notification notification, ThemeData theme, Color mutedColor) {
    IconData icon;
    Color color;

    bool isDefeat = notification.title.toLowerCase().contains('failed') || 
                    notification.title.toLowerCase().contains('defeat') ||
                    notification.title.toLowerCase().contains('lost');

    switch (notification.type) {
      case 'friend_request':
        icon = Icons.person_add;
        color = Colors.blueAccent;
        break;
      case 'match_result':
        if (isDefeat) {
            icon = Icons.sentiment_very_dissatisfied;
            color = Colors.redAccent;
        } else {
            icon = Icons.emoji_events;
            color = Colors.amber; // Golden Trophy
        }
        break;
      default:
        icon = Icons.info_outline;
        color = mutedColor;
    }

    return Dismissible(
      key: Key(notification.id.toString()),
      background: Container(color: Colors.red),
      onDismissed: (direction) {
        // Implement delete if needed, for now just hide
      },
      child: Container(
        color: notification.isRead ? Colors.transparent : theme.colorScheme.surface.withValues(alpha: 0.3),
        child: ListTile(
          leading: CircleAvatar(
            backgroundColor: color.withValues(alpha: 0.1),
            child: Icon(icon, color: color, size: 20),
          ),
          title: Text(
            notification.title,
            style: TextStyle(
              color: theme.colorScheme.onSurface,
              fontWeight: notification.isRead ? FontWeight.normal : FontWeight.bold,
            ),
          ),
          subtitle: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              const SizedBox(height: 4),
              Text(
                notification.message,
                maxLines: 2,
                overflow: TextOverflow.ellipsis,
                style: TextStyle(color: notification.isRead ? mutedColor : theme.colorScheme.onSurface.withValues(alpha: 0.7)),
              ),
              const SizedBox(height: 4),
              Text(
                DateFormat.yMMMd().add_jm().format(notification.createdAt),
                style: TextStyle(color: mutedColor, fontSize: 10),
              ),
              if (notification.type == 'friend_request' && !notification.isRead)
                Padding(
                  padding: const EdgeInsets.only(top: 8),
                  child: Row(
                    children: [
                      ElevatedButton(
                        onPressed: () => _handleFriendRequest(notification, true),
                        style: ElevatedButton.styleFrom(
                          backgroundColor: theme.primaryColor,
                          foregroundColor: theme.colorScheme.onPrimary,
                          minimumSize: const Size(80, 32),
                          padding: const EdgeInsets.symmetric(horizontal: 12),
                        ),
                        child: const Text('Accept'),
                      ),
                      const SizedBox(width: 8),
                      OutlinedButton(
                        onPressed: () => _handleFriendRequest(notification, false),
                        style: OutlinedButton.styleFrom(
                          foregroundColor: Colors.redAccent,
                          side: const BorderSide(color: Colors.redAccent),
                          minimumSize: const Size(80, 32),
                          padding: const EdgeInsets.symmetric(horizontal: 12),
                        ),
                        child: const Text('Reject'),
                      ),
                    ],
                  ),
                ),
            ],
          ),
          onTap: () async {
            await _markAsRead(notification);
            if (!context.mounted) return;
            _showNotificationDialog(notification, theme);
          },
        ),
      ),
    );
  }
}
