class GameDataLocalizer {
  static String localize(String original, String locale) {
    final Map<String, Map<String, String>> dictionary = {
      'pt': {
        // Categories
        'Medieval': 'Medieval',
        'Territory Building': 'Construção de Território',
        'Economic': 'Econômico',
        'Fantasy': 'Fantasia',
        'Card Game': 'Jogo de Cartas',
        'Fighting': 'Luta',
        'Adventure': 'Aventura',
        'Exploration': 'Exploração',
        'Farming': 'Fazenda',
        'Civilization': 'Civilização',
        'Ancient': 'Antiguidade',
        'City Building': 'Construção de Cidades',
        'Animal': 'Animais',
        // Mechanics
        'Area Majority / Influence': 'Maioria de Área / Influência',
        'Enclosure': 'Cercamento',
        'Kill Steal': 'Eliminação Progressiva',
        'Map Addition': 'Adição de Mapa',
        'Pattern Building': 'Construção de Padrões',
        'Tile Placement': 'Alocação de Peças',
        'Hand Management': 'Gestão de Mão',
        'Dice Rolling': 'Rolagem de Dados',
        'Worker Placement': 'Alocação de Trabalhadores',
        'Cooperative Game': 'Jogo Cooperativo',
        'Solo / Solitaire Game': 'Jogo Solo',
        'Deck, Bag, and Pool Building': 'Construção de Baralho / Reserva',
        'Set Collection': 'Coleção de Conjuntos',
        'Action Points': 'Pontos de Ação',
        // Classification
        'Family Games': 'Jogos Familiares',
        'Strategy Games': 'Jogos de Estratégia',
        'Thematic Games': 'Jogos Temáticos',
        'Party Games': 'Jogos de Festa',
        'Wargames': 'Jogos de Guerra',
        'Customizable Games': 'Jogos Customizáveis',
        'Children\'s Games': 'Jogos Infantis',
        'Abstract Games': 'Jogos Abstratos',
      },
      'en': {
        // EN stays English but we can map for normalization if needed
      },
      'de': {
        // Categories
        'Medieval': 'Mittelalter',
        'Territory Building': 'Gebietsbau',
        'Economic': 'Wirtschaft',
        'Fantasy': 'Fantasy',
        'Card Game': 'Kartenspiel',
        'Fighting': 'Kampf',
        'Adventure': 'Abenteuer',
        'Exploration': 'Erkundung',
        'Farming': 'Landwirtschaft',
        'Civilization': 'Zivilisation',
        'Ancient': 'Antike',
        'City Building': 'Städtebau',
        'Animal': 'Tiere',
        // Mechanics
        'Area Majority / Influence': 'Mehrheitenkontrolle / Einfluss',
        'Enclosure': 'Umzingelung',
        'Kill Steal': 'Kill Steal',
        'Map Addition': 'Kartenergänzung',
        'Pattern Building': 'Musterbildung',
        'Tile Placement': 'Plättchenlegen',
        'Hand Management': 'Handmanagement',
        'Dice Rolling': 'Würfeln',
        'Worker Placement': 'Arbeitereinsetzen',
        'Cooperative Game': 'Kooperatives Spiel',
        'Solo / Solitaire Game': 'Solospiel',
        'Deck, Bag, and Pool Building': 'Deck-, Bag- und Pool-Building',
        'Set Collection': 'Set-Sammlung',
        'Action Points': 'Aktionspunkte',
        // Classification
        'Family Games': 'Familienspiele',
        'Strategy Games': 'Strategiespiele',
        'Thematic Games': 'Thematische Spiele',
        'Party Games': 'Partyspiele',
        'Wargames': 'Wargames',
        'Customizable Games': 'Anpassbare Spiele',
        'Children\'s Games': 'Kinderspiele',
        'Abstract Games': 'Abstrakte Spiele',
      },
      'fr': {
        // Categories
        'Medieval': 'Médiéval',
        'Territory Building': 'Construction de Territoire',
        'Economic': 'Économique',
        'Fantasy': 'Fantaisie',
        'Card Game': 'Jeu de Cartes',
        'Fighting': 'Combat',
        'Adventure': 'Aventure',
        'Exploration': 'Exploration',
        'Farming': 'Agriculture',
        'Civilization': 'Civilisation',
        'Ancient': 'Antiquité',
        'City Building': 'Construction de Ville',
        'Animal': 'Animaux',
        // Mechanics
        'Area Majority / Influence': 'Majorité / Influence',
        'Enclosure': 'Enclos',
        'Kill Steal': 'Kill Steal',
        'Map Addition': 'Ajout de Carte',
        'Pattern Building': 'Construction de Motifs',
        'Tile Placement': 'Pose de Tuiles',
        'Hand Management': 'Gestion de Main',
        'Dice Rolling': 'Lancer de Dés',
        'Worker Placement': 'Placement d\'Ouvriers',
        'Cooperative Game': 'Jeu Coopératif',
        'Solo / Solitaire Game': 'Jeu Solo',
        'Deck, Bag, and Pool Building': 'Construction de Deck / Pool',
        'Set Collection': 'Collection de Sets',
        'Action Points': 'Points d\'Action',
        // Classification
        'Family Games': 'Jeux Familiaux',
        'Strategy Games': 'Jeux de Stratégie',
        'Thematic Games': 'Jeux Thématiques',
        'Party Games': 'Jeux d\'Ambiance',
        'Wargames': 'Jeux de Guerre',
        'Customizable Games': 'Jeux Personnalisables',
        'Children\'s Games': 'Jeux pour Enfants',
        'Abstract Games': 'Jeux Abstraits',
      }
    };

    if (!dictionary.containsKey(locale)) return original;
    return dictionary[locale]![original] ?? original;
  }
}
